/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'background': '#fcf9f8',
        'surface': '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'surface-variant': '#e5e2e1',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#434842',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        'outline': '#747872',
        'outline-variant': '#c4c8c0',
        'primary': '#516051',
        'on-primary': '#ffffff',
        'primary-container': '#6a7869',
        'on-primary-container': '#f7fff3',
        'primary-fixed': '#d7e7d4',
        'primary-fixed-dim': '#bbcbb9',
        'on-primary-fixed': '#121e13',
        'on-primary-fixed-variant': '#3c4a3d',
        'inverse-primary': '#bbcbb9',
        'secondary': '#5e5f5c',
        'on-secondary': '#ffffff',
        'secondary-container': '#e0e0dc',
        'on-secondary-container': '#626360',
        'secondary-fixed': '#e3e2df',
        'secondary-fixed-dim': '#c7c7c3',
        'on-secondary-fixed': '#1b1c1a',
        'on-secondary-fixed-variant': '#464744',
        'tertiary': '#555e55',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#6d776d',
        'on-tertiary-container': '#f6fff3',
        'tertiary-fixed': '#dbe5d9',
        'tertiary-fixed-dim': '#bfc9bd',
        'on-tertiary-fixed': '#151e16',
        'on-tertiary-fixed-variant': '#404940',
        'surface-tint': '#546254',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'bg-primary': '#fcf9f8',
        'bg-secondary': '#f6f3f2',
        'bg-card': '#f6f3f2',
        'bg-border': '#e5e2e1',
        'text-primary': '#1c1b1b',
        'text-secondary': '#434842',
        'text-muted': '#747872',
        'accent-lime': '#516051',
        'accent-lime-dark': '#6a7869',
        'accent-lime-muted': 'rgba(81,96,81,0.1)',
        'status-danger': '#ba1a1a',
        'status-warning': '#747872',
        'status-success': '#516051',
      },
      fontFamily: {
        'display-lg': ['Literata', 'serif'],
        'display-lg-mobile': ['Literata', 'serif'],
        'headline-md': ['Literata', 'serif'],
        'headline-sm': ['Literata', 'serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
      },
      spacing: {
        'container-padding': '24px',
        'stack-gap-sm': '8px',
        'stack-gap-md': '16px',
        'stack-gap-lg': '32px',
        'section-margin': '48px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        'card': '0 10px 40px -10px rgba(26, 26, 26, 0.05)',
        'sheet': '0 -8px 40px rgba(26, 26, 26, 0.12)',
      },
    },
  },
  plugins: [],
};
