/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-primary': '#0A0A0F',
        'bg-secondary': '#111118',
        'bg-card': '#1A1A24',
        'bg-border': '#2A2A35',
        'accent-lime': '#A8FF3E',
        'accent-lime-dark': '#7ACC20',
        'accent-lime-muted': '#A8FF3E1A',
        'text-primary': '#FFFFFF',
        'text-secondary': '#8B8B9E',
        'text-muted': '#4A4A5A',
        'status-warning': '#F59E0B',
        'status-danger': '#EF4444',
        'status-success': '#A8FF3E',
        primary: '#ffffff',
        'primary-fixed': '#c3f400',
        'primary-fixed-dim': '#abd600',
        'on-primary': '#283500',
        'on-primary-fixed': '#161e00',
        background: '#131313',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-bright': '#3a3939',
        'surface-variant': '#353534',
        'surface-tint': '#abd600',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c4c9ac',
        secondary: '#c8c6c5',
        'secondary-container': '#474746',
        'on-secondary': '#313030',
        'on-secondary-container': '#b7b5b4',
        outline: '#8e9379',
        'outline-variant': '#444933',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-tertiary-container': '#b7b5b4',
        'secondary-fixed-dim': '#c8c6c5',
      },
      fontFamily: {
        display: ['Sora', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600', letterSpacing: '-0.01em' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0.01em' }],
        'label-sm': ['12px', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '0.05em' }],
      },
      spacing: {
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '48px',
        gutter: '16px',
        'container-padding-mobile': '20px',
      },
      borderRadius: {
        DEFAULT: '4px',
        lg: '8px',
        xl: '12px',
        full: '9999px',
      },
      backgroundColor: {
        primary: '#0A0A0F',
        secondary: '#111118',
        card: '#1A1A24',
        border: '#2A2A35',
      },
      textColor: {
        primary: '#FFFFFF',
        secondary: '#8B8B9E',
        muted: '#4A4A5A',
      },
    },
  },
  plugins: [],
};
